name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["master", "master"]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lints:
    name: lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        # Ensure rustfmt is installed and setup problem matcher
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy,cargo-tarpaulin
          toolchain: nightly

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Generate code coverage
        run: cargo tarpaulin --verbose --engine llvm --ignore-tests --out Lcov --output-dir target/lcov

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: target/lcov/lcov.info
